services:
  - type: web
    name: workora
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn WorkOra.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
    postdeploy: |
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); \
if not User.objects.filter(username='admin').exists(): \
  User.objects.create_superuser('admin', 'admin@example.com', 'adminpassword123')" \
 | python manage.py shell
