services:
  - type: web
    name: workora
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn WorkOra.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
    postdeploy: python manage.py migrate

