# Generated by Django 5.1.7 on 2025-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Urgent', 'Urgent'), ('New', 'New')], default='Full-Time', max_length=20),
        ),
    ]
