# Generated by Django 5.1.7 on 2025-06-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='detail_intro',
            new_name='skill_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='detail_responsibilities',
        ),
        migrations.AddField(
            model_name='job',
            name='salaryPeriod',
            field=models.CharField(choices=[('Daily', 'Weekly'), ('Monthly', 'Year')], default='Daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Urgent', 'Urgent'), ('New', 'New'), ('Contract', 'Daily Wages')], default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('0-1 Years', '0-1 Years'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '5+ Years')], default='No Experience', max_length=20),
        ),
    ]
