# Generated by Django 5.1.7 on 2025-06-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_detail_intro_job_skill_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Urgent', 'Urgent'), ('Contract', 'Contract')], default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('0-1 Years', '0-1 Years'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('5+ years', '5+ years')], default='No Experience', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryPeriod',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Daily', max_length=20),
        ),
    ]
